version: "3"

tasks:
  cleanup-generated-mirror-node-models:
    desc: Cleans up generated OpenAPI files and reorganizes the structure
    cmds:
      # Remove core and services directories
      - rm -rf src/utils/models/mirror-node-models/core
      - rm -rf src/utils/models/mirror-node-models/services

      # Move all files from models directory to mirror-node-models
      - mv src/utils/models/mirror-node-models/models/* src/utils/models/mirror-node-models/

      # Remove the now-empty models directory
      - rm -rf src/utils/models/mirror-node-models/models

      # Update index.ts using Node.js
      - node -e "
        const fs = require('fs');
        const path = 'src/utils/models/mirror-node-models/index.ts';
        let content = fs.readFileSync(path, 'utf8');
        content = content.split('\n')
        .filter(line => !line.includes('/core/') && !line.includes('/services/'))
        .map(line => line.replace('./models/', './'))
        .join('\n');
        fs.writeFileSync(path, content);
        "
  status:
    - test ! -d src/utils/models/mirror-node-models

  generate-mirror-node-models:
    desc: Generates OpenAPI models and cleans up the structure
    cmds:
      - npm run generate-mirror-node-models
      - task: cleanup-generated-mirror-node-models

  tag-previous-version:
    desc: Tags the current 'latest' Docker image with a specific version number
    silent: true
    vars:
      VERSION: "{{.VERSION}}"
    cmds:
      - echo "Pulling latest Docker image from DockerHub"
      - docker pull ivaylogarnev/hiero-tck-client:latest
      - echo "Tagging latest image as version {{.VERSION}}"
      - docker tag ivaylogarnev/hiero-tck-client:latest ivaylogarnev/hiero-tck-client:{{.VERSION}}
      - echo "Pushing tagged image to DockerHub"
      - docker push ivaylogarnev/hiero-tck-client:{{.VERSION}}
    preconditions:
      - sh: test -n "{{.VERSION}}"
        msg: "VERSION parameter is required. Usage: task tag-previous-version VERSION=x.y.z"

  release-hiero-tck-client:
    desc: Builds and pushes a new Docker image with the 'latest' tag to DockerHub
    silent: true
    cmds:
      - echo "Building Docker image hiero-tck-client:latest"
      - docker build -t ivaylogarnev/hiero-tck-client:latest -f Dockerfile .
      - echo "Pushing Docker image to DockerHub"
      - docker push ivaylogarnev/hiero-tck-client:latest
