title: Hiero TCK Docs
description: TCK docs for Hiero
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: https://lukebair.github.io/hiero-sdk-tck

aux_links:
  Github Repository: https://github.com/hiero-ledger/hiero-sdk-tck

#nav_enabled: false
