name: Start All Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-all-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Start local Hedera network
        run: |
          ionice -c 2 -n 2 nice -n 19 npx @hashgraph/hedera-local start -d --network local --balance=10000000
          sleep 30

      - name: Pull JS TCK Server
        run: |
          docker pull ivaylogarnev/js-tck-server

      - name: Start Docker Compose services
        run: docker compose -f ./docker-compose.yml up --abort-on-container-exit

      - name: Stop the local node
        if: ${{ always() }}
        run: ionice -c 2 -n 2 nice -n 19 npx @hashgraph/hedera-local stop
