name: TCK Test Count

on:
  pull_request:
    paths:
      - "docs/test-specifications/**"
      - "src/tests/**"
      - "testCount.js"
      - "package.json"
      - "package-lock.json"
  push:
    branches:
       - main
       - feat/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run test count script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -o pipefail
          echo "Running testCount.js…"
          npm run -s test:count | tee test-count.log
          echo
          echo "----- Raw Output Above -----"

      - name: Show results
        if: always()
        run: |
          {
            echo "## TCK Test Count Results"
            echo
            echo '```text'
            cat test-count.txt
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

