name: Start All Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CG_EXEC: ionice -c 2 -n 2 nice -n 19

jobs:
  start-all-tests:
    name: Run tests for regressions
    runs-on: hiero-client-sdk-linux-medium
    strategy:
      matrix:
        node: ["20", "22"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      # Note: After Step-Security is enabled return to step-security/action-setup version
      - name: Install PNPM
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 9.15.5

      - name: Setup Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Start the local node
        id: start-local-node
        run: |
          ${{ env.CG_EXEC }} npx @hashgraph/hedera-local start -d --network local --balance=100000 --network-tag=0.60.0-alpha.0
          sleep 30

      - name: Pull Docker images
        run: |
          docker pull ivaylogarnev/tck-client
          docker pull ivaylogarnev/js-tck-server

      - name: Start Docker Compose services
        run: docker compose -f ./docker-compose.yml up --abort-on-container-exit

      - name: Stop the local node
        id: stop-local-node
        run: ${{ env.CG_EXEC }} npx @hashgraph/hedera-local stop
