name: Run TCK Test Suites in Parallel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: hiero-client-sdk-linux-large
    strategy:
      matrix:
        suite:
          - AccountCreate
          - AccountUpdate
          - AccountDelete
          - AccountAllowanceDelete
          - AccountAllowanceApprove
          - TokenCreate
          - TokenUpdate
          - TokenDelete
          - TokenBurn
          - TokenMint
          - TokenAssociate
          - TokenDissociate
          - TokenFeeScheduleUpdate
          - TokenGrantKyc
          - TokenRevokeKyc
          - TokenPause
          - TokenUnpause
          - TokenFreeze
          - TokenUnfreeze
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Start local Hedera network
        run: |
          ionice -c 2 -n 2 nice -n 19 npx @hashgraph/hedera-local start -d \
            --network local \
            --balance=10000000 \
            --cache-dir=/tmp/hedera-cache
          sleep 25

      - name: Pull JS TCK Server
        run: |
          docker pull ivaylogarnev/js-tck-server-amd

      - name: Start tck-server in background
        run: |
          TEST=${{ matrix.suite }} docker compose -f ./docker-compose.yml up -d tck-server

      - name: Wait for tck-server to become healthy
        run: |
          # Show container logs for debugging
          docker compose -f ./docker-compose.yml logs tck-server

          # Check container status
          docker ps

          # Try with longer timeout and more detailed output
          timeout 120s bash -c "while true; do 
            status=\$(docker inspect --format='{{.State.Health.Status}}' \$(docker compose -f ./docker-compose.yml ps -q tck-server) 2>/dev/null)
            echo \"Current health status: \$status\"
            if [ \"\$status\" = \"healthy\" ]; then
              echo 'tck-server is healthy!'
              break
            fi
            # Show last health check result
            docker inspect --format='{{json .State.Health}}' \$(docker compose -f ./docker-compose.yml ps -q tck-server) | jq
            sleep 10
            echo 'Waiting for tck-server...'
          done"

          if [ $? -ne 0 ]; then 
            echo "tck-server failed to become healthy within timeout"
            docker compose -f ./docker-compose.yml logs tck-server
            exit 1
          fi

      - name: Run ${{ matrix.suite }} tests
        run: |
          TEST=${{ matrix.suite }} docker compose -f ./docker-compose.yml up \
            --abort-on-container-exit \
            --exit-code-from tck-client tck-client

      - name: Stop the local node and containers
        if: ${{ always() }}
        run: |
          docker compose -f ./docker-compose.yml down --volumes 
          ionice -c 2 -n 2 nice -n 19 npx @hashgraph/hedera-local stop
