name: Start All Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Start local Hedera network
        run: |
          ionice -c 2 -n 2 nice -n 19 npx @hashgraph/hedera-local start -d --network local --balance=10000000
          sleep 30

      - name: Pull Docker images
        run: |
          docker pull ivaylogarnev/tck-client
          docker pull ivaylogarnev/js-tck-server

      - name: Create Docker Compose file
        run: |
          echo "
          version: '3.8'
          services:
            tck-server:
              image: ivaylogarnev/js-tck-server
              platform: linux/amd64
              networks:
                - hedera-network-node
                - hedera-mirror-node
              environment:
                NETWORK: \"\${NETWORK:-local}\"
              ports:
                - \"8544:8544\"
            tck-client:
              image: ivaylogarnev/tck-client
              platform: linux/amd64
              networks:
                - hedera-network-node
                - hedera-mirror-node
              environment:
                TEST: \"\${TEST:-ALL}\"
                NETWORK: \"\${NETWORK:-local}\"
                OPERATOR_ACCOUNT_ID: \"\${OPERATOR_ACCOUNT_ID:-0.0.1022}\"
                OPERATOR_ACCOUNT_PRIVATE_KEY: \"\${OPERATOR_ACCOUNT_PRIVATE_KEY:-302e020100300506032b657004220420a608e2130a0a3cb34f86e757303c862bee353d9ab77ba4387ec084f881d420d4}\"
                JSON_RPC_SERVER_URL: \"http://tck-server:8544\"
                NODE_IP: \"network-node:50211\"
                MIRROR_NODE_REST_URL: \"\${MIRROR_NODE_REST_URL:-http://mirror-node-rest:5551}\"
                MIRROR_NODE_REST_JAVA_URL: \"\${MIRROR_NODE_REST_JAVA_URL:-http://mirror-node-rest-java:8084}\"
              depends_on:
                - tck-server
          networks:
            hedera-network-node:
              external: true
            hedera-mirror-node:
              external: true
          " > docker-compose.yml

      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Stop the local node
        if: ${{ !cancelled() && always() }}
        run: ionice -c 2 -n 2 nice -n 19 npx @hashgraph/hedera-local stop
