name: Run TCK Test Suites in Parallel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: hiero-client-sdk-linux-large
    strategy:
      matrix:
        suite:
          - AccountCreate
          - AccountUpdate
          - AccountDelete
          - AccountAllowanceDelete
          - AccountAllowanceApprove
          - TokenCreate
          - TokenUpdate
          - TokenDelete
          - TokenBurn
          - TokenMint
          - TokenAssociate
          - TokenDissociate
          - TokenFeeScheduleUpdate
          - TokenGrantKyc
          - TokenRevokeKyc
          - TokenPause
          - TokenUnpause
          - TokenFreeze
          - TokenUnfreeze
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Start local Hedera network
        run: |
          ionice -c 2 -n 2 nice -n 19 npx @hashgraph/hedera-local start -d \
            --network local \
            --balance=10000000 \
            --cache-dir=/tmp/hedera-cache

      - name: Pull JS TCK Server
        run: |
          docker pull ivaylogarnev/js-tck-server-amd

      - name: Start tck-server in background
        run: |
          TEST=${{ matrix.suite }} docker compose -f ./docker-compose.yml up -d tck-server

          # Get container ID
          container_id=$(docker compose -f ./docker-compose.yml ps -q tck-server)
          if [ -z "$container_id" ]; then
            echo "Error: Failed to start tck-server container"
            docker compose -f ./docker-compose.yml logs tck-server
            exit 1
          fi

          # Check if container is running
          max_attempts=30
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            if docker inspect $container_id | grep -q '"Running": true'; then
              echo "tck-server is running (container ID: $container_id)"
              
              # Verify port is listening
              if docker exec $container_id nc -z localhost 8544; then
                echo "tck-server is responding on port 8544"
                break
              else
                echo "Waiting for tck-server to respond on port 8544 (attempt $attempt/$max_attempts)"
              fi
            else
              echo "tck-server container is not running (attempt $attempt/$max_attempts)"
              docker compose -f ./docker-compose.yml logs tck-server
              exit 1
            fi
            
            if [ $attempt -eq $max_attempts ]; then
              echo "Error: tck-server failed to become ready after $max_attempts attempts"
              docker compose -f ./docker-compose.yml logs tck-server
              exit 1
            fi
            attempt=$((attempt + 1))
          done

      - name: Run ${{ matrix.suite }} tests
        run: |
          TEST=${{ matrix.suite }} docker compose -f ./docker-compose.yml up \
            --abort-on-container-exit \
            --exit-code-from tck-client tck-client

      - name: Stop the local node and containers
        if: ${{ always() }}
        run: |
          docker compose -f ./docker-compose.yml down --volumes 
          ionice -c 2 -n 2 nice -n 19 npx @hashgraph/hedera-local stop
