name: Run TCK Test Suites in Parallel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: hiero-client-sdk-linux-large
    strategy:
      matrix:
        suite:
          - AccountAllowanceApprove
          - AccountAllowanceDelete
          - AccountCreate
          - AccountDelete
          - AccountUpdate
          - FileAppend
          - FileCreate
          - FileUpdate
          - TokenAirdropCancel
          - TokenAirdropClaim
          - TokenAirdrop
          - TokenAssociate
          - TokenBurn
          - TokenCreate
          - TokenDelete
          - TokenDissociate
          - TokenFeeScheduleUpdate
          - TokenFreeze
          - TokenGrantKyc
          - TokenMint
          - TokenPause
          - TokenReject
          - TokenRevokeKyc
          - TokenUnfreeze
          - TokenUnpause
          - TokenUpdate
          - TokenWipe
          - TransferCrypto
          - TopicCreate
          - TopicDelete
          - TopicMessageSubmit
          - TopicUpdate
          - ContractCreate
          - ContractUpdate
          - ContractDelete
          - ContractExecute
          - ScheduleCreate
          - ScheduleSign
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Kind
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          install_only: true
          node_image: kindest/node:v1.31.4@sha256:2cb39f7295fe7eafee0842b1052a599a4fb0f8bcf3f83d96c7f4864c357c6c30
          version: v0.26.0
          kubectl_version: v1.31.4
          verbosity: 3
          wait: 120s

      - name: Install Solo CLI
        run: |
          set -euo pipefail
          npm install -g @hashgraph/solo
          solo --version
          kind --version

      - name: Deploy Solo
        id: solo_deploy
        env:
          SOLO_CLUSTER_NAME: solo
          SOLO_NAMESPACE: solo
          SOLO_CLUSTER_SETUP_NAMESPACE: solo-cluster
          SOLO_DEPLOYMENT: solo-deployment
        run: |
          set -euo pipefail
          kind create cluster -n "${SOLO_CLUSTER_NAME}"
          solo quick-start single deploy | tee solo-deploy.log

      - name: Check port forwarding
        run: |
          ps -ef | grep port-forward
          env
          curl -fsS http://localhost:8080/api/v1/network/nodes
          curl -fsS http://localhost:8081/api/v1/network/nodes
      # TODO: Update this once we have a dynamically updated image
      - name: Pull JS TCK Server
        run: |
          docker pull ivaylogarnev/js-tck-server-amd

      - name: Start tck-server in background
        run: |
          TEST=${{ matrix.suite }} docker compose -f ./docker-compose.yml up -d tck-server

      - name: Wait for TCK server
        run: |
          echo "Waiting for TCK server on port 8544..."
          until bash -c 'exec 3>/dev/tcp/localhost/8544'; do
            echo "Still waiting..."
            sleep 1
          done
          echo "TCK server is ready!"

      - name: Run ${{ matrix.suite }} tests
        run: |
          TEST=${{ matrix.suite }} docker compose -f ./docker-compose.yml up \
            --abort-on-container-exit \
            --exit-code-from hiero-tck-client hiero-tck-client
            
      - name: Stop the local node and containers
        if: ${{ always() }}
        run: |
          docker compose -f ./docker-compose.yml down --volumes 
          ionice -c 2 -n 2 nice -n 19 npx @hashgraph/hedera-local stop